// Generated by scripts/prep-ink.mjs — do not edit.
import d0 from './bridge.json';
import d1 from './crossroads-signpost.json';
import d2 from './desk-clock.json';
import d3 from './dock.json';
import d4 from './house.json';
import d5 from './ledger-page.json';
import d6 from './lighthouse.json';
import d7 from './path.json';
import d8 from './road-markers.json';
import d9 from './sailboat.json';
import d10 from './system-map.json';
import d11 from './travel-bag.json';
import d12 from './two-chairs.json';
import d13 from './workshop-notebook.json';

export const DRAWINGS = {
  'bridge': d0 as InkData,
  'crossroads-signpost': d1 as InkData,
  'desk-clock': d2 as InkData,
  'dock': d3 as InkData,
  'house': d4 as InkData,
  'ledger-page': d5 as InkData,
  'lighthouse': d6 as InkData,
  'path': d7 as InkData,
  'road-markers': d8 as InkData,
  'sailboat': d9 as InkData,
  'system-map': d10 as InkData,
  'travel-bag': d11 as InkData,
  'two-chairs': d12 as InkData,
  'workshop-notebook': d13 as InkData,
};
export type DrawingName = keyof typeof DRAWINGS;

export type StrokeKind = 'ink' | 'inkSoft' | 'hatch' | 'hatchSoft' | 'pencil';
export type InkStroke = { kind: StrokeKind; g: number; d: string; len: number; box: [number, number, number, number]; nib?: number; w?: number; o?: number };
export type InkWash = { tone: string; opacity: number; d: string };
export type InkData = { name: string; viewBox: number[]; washes: InkWash[]; strokes: InkStroke[] };
