// Generated by scripts/prep-ink.mjs — do not edit.
import d0 from './bridge.json';
import d1 from './dock.json';
import d2 from './house.json';
import d3 from './lighthouse.json';
import d4 from './path.json';
import d5 from './sailboat.json';
import d6 from './travel-bag.json';
import d7 from './two-chairs.json';

export const DRAWINGS = {
  'bridge': d0 as InkData,
  'dock': d1 as InkData,
  'house': d2 as InkData,
  'lighthouse': d3 as InkData,
  'path': d4 as InkData,
  'sailboat': d5 as InkData,
  'travel-bag': d6 as InkData,
  'two-chairs': d7 as InkData,
};
export type DrawingName = keyof typeof DRAWINGS;

export type StrokeKind = 'ink' | 'inkSoft' | 'hatch' | 'hatchSoft' | 'pencil';
export type InkStroke = { kind: StrokeKind; g: number; d: string; len: number; box: [number, number, number, number]; nib?: number; w?: number; o?: number };
export type InkWash = { tone: string; opacity: number; d: string };
export type InkData = { name: string; viewBox: number[]; washes: InkWash[]; strokes: InkStroke[] };
